In [1]:
import numpy as np
import pandas as pd

In [2]:
x = np.array([0, 1, 2, 3])
x

array([0, 1, 2, 3])

In [3]:
w = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
y = np.arange(8).reshape(2, 4)
y

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
x = np.array([0, 1, 2, 3])

#Square each value.
print(np.square(x))

#Square root of each value. 
print(np.sqrt(x))

#cosine of each value.
print(np.cos(x))

[0 1 4 9]
[0.         1.         1.41421356 1.73205081]
[ 1.          0.54030231 -0.41614684 -0.9899925 ]


In [6]:
x = np.array([0, 1, 2, 3])

#Find the maximum value. 
print(np.max(x))

#Find the minimum value. 
print(np.min(x))

#Find the mean of an input array.
print(np.mean(x))

#Find the standard deviation of the input array. 
print(np.std(x))

3
0
1.5
1.118033988749895


In [8]:
my_array = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
df = pd.DataFrame(my_array)
df

0  1  2  3
0  0  1  2  3
1  4  5  6  7

In [10]:
df.columns = ['first', 'this', 'that', 'last']
df.index = ['row_1', 'row_2']
df


first  this  that  last
row_1      0     1     2     3
row_2      4     5     6     7

In [12]:
#Can also set C&I names through DataFrame
df2 = pd.DataFrame(
    my_array,
    columns=['first', 'this', 'that', 'last'],
    index=['row_1', 'row_2'])
df2

first  this  that  last
row_1      0     1     2     3
row_2      4     5     6     7

In [13]:
names =['George',
        'John',
        'Thomas',
        'James',
        'Andrew',
        'Martin',
        'William',
        'Zachary',
        'Millard',
        'Franklin']
#Create an empty data frame with named rows. 
purchases = pd.DataFrame(index=names)

#Add our columns to the data frame one at a time. 
purchases['country'] = ['US', 'CAN', 'CAN', 'US', 'CAN', 'US', 'US', 'US', 'CAN','US']
purchases['ad_views'] = [16, 42, 32, 13, 63, 19, 65, 23, 16, 77]
purchases['items_purchased'] = [2, 1, 0, 8, 0, 5, 7, 3, 0, 5]
purchases

country  ad_views  items_purchased
George        US        16                2
John         CAN        42                1
Thomas       CAN        32                0
James         US        13                8
Andrew       CAN        63                0
Martin        US        19                5
William       US        65                7
Zachary       US        23                3
Millard      CAN        16                0
Franklin      US        77                5

In [14]:
purchases['items_purch_per_ad'] = purchases['items_purchased'] / purchases['ad_views']
purchases

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
John         CAN        42                1            0.023810
Thomas       CAN        32                0            0.000000
James         US        13                8            0.615385
Andrew       CAN        63                0            0.000000
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Millard      CAN        16                0            0.000000
Franklin      US        77                5            0.064935

In [15]:
purchases['items_purchased'] / purchases['ad_views']


George      0.125000
John        0.023810
Thomas      0.000000
James       0.615385
Andrew      0.000000
Martin      0.263158
William     0.107692
Zachary     0.130435
Millard     0.000000
Franklin    0.064935
dtype: float64

In [16]:
purchases.loc['George']

country                  US
ad_views                 16
items_purchased           2
items_purch_per_ad    0.125
Name: George, dtype: object

In [17]:
purchases.loc[:, 'country']

George       US
John        CAN
Thomas      CAN
James        US
Andrew      CAN
Martin       US
William      US
Zachary      US
Millard     CAN
Franklin     US
Name: country, dtype: object

In [18]:
purchases.loc['George', 'country']

'US'

In [19]:
purchases.iloc[1:3, 1]

John      42
Thomas    32
Name: ad_views, dtype: int64

In [20]:
purchases.loc[lambda df: purchases['items_purchased'] > 1, :]

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
James         US        13                8            0.615385
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Franklin      US        77                5            0.064935

In [21]:
#boolean logic is easier to get teh same result
purchases[purchases['items_purchased'] > 1]

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
James         US        13                8            0.615385
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Franklin      US        77                5            0.064935

In [22]:
purchases.groupby('country')

In [25]:
purchases.groupby('country').aggregate(np.mean)
#if you don't want all the columns use 
#purchases.groupby('country')['column_name'].mean()

country
CAN    38.25
US     35.50
Name: ad_views, dtype: float64

In [27]:
df = pd.read_csv('purchases.csv')
print (df)

  Unnamed: 0 country  ad_views  items_purchased
0     George      US        16                2
1       John     CAN        42                1
2     Thomas     CAN        32                0
3      James      US        13                8
4     Andrew     CAN        63                0
5     Martin      US        19                5
6    William      US        65                7
7    Zachary      US        23                3
8    Millard     CAN        16                0
9   Franklin      US        77                5


In [28]:
#to create a csv file and write your dataframe to it's use
df.to_csv('my_data.csv')

In [34]:
df = pd.read_json('purchases.json')
df

Unnamed: 0  ad_views country  items_purchased
0     George        16      US                2
1       John        42     CAN                1
2     Thomas        32     CAN                0
3      James        13      US                8
4     Andrew        63     CAN                0
5     Martin        19      US                5
6    William        65      US                7
7    Zachary        23      US                3
8    Millard        16     CAN                0
9   Franklin        77      US                5